### ISSUE TITLE
Bug on fresh install when enabling `jq`

### ISSUE THREAD

**Issue by zph** [digital-asset/dev-env#1]
Hi and thank you for open sourcing this toolkit.

When I tried out dev-env today, I hit a bug with my first binary I enabled.

Environment:
- Mac
- nix-env (Nix) 2.3.7
- direnv version 2.19.2

Reproduction steps (following readme and using a Mac):
```
curl -sL https://github.com/digital-asset/dev-env/archive/main.tar.gz | tar xzf - --strip-components=1 dev-env-main/dev-env dev-env-main/.envrc
  direnv allow

# Enable jq in default.nix
# Create symlink when PWD=../dev-env
ln -s ../lib/dade-exec-nix-tool dev-env/bin/jq
```

At this point an `ls -lah` gives the following result:
```
lrwxr-xr-x  1 me  staff    25B Jan 30 12:53 dev-env/bin/jq@ -> ../lib/dade-exec-nix-tool
```

If I execute `jq` I get the following failure:

```
[dev-env] Building tools.jq...
[dev-env] Built tools.jq in /nix/store/msxm3ssbk0anbmdqlb6cvfxlpjwpys67-jq-1.6-bin and linked to /Users/zph/src/testing/dev-env/var/gc-roots/jq
/Users/zph/src/testing/dev-env/bin/../lib/dade-common: line 133: /bin/jq: No such file or directory
```

Line 133 is:
```
exec "$(readlink "$DADE_BUILD_RESULT")/bin/$binary" "$@"
```

When I debug it, my jq binary isn't at that location and I can fix it by patching L133 as:

```
exec "${DADE_BUILD_RESULT}-bin/bin/$binary" "$@"
```

(Note the path difference)

When debugging further, I see that the readlink invocation is returning an empty string but the $DADE_BUILD_RESULT is present.

Please let me know if I can help with debugging and I'll experiment a bit more w/ the project. I saw the PRs not accepted note in readme so filing this as an Issue in case you're interested. Thanks 👍

**Comment by garyverhaegen-da** [comment]
Hi @zph,

Terribly sorry I missed this. This is sort of a known issue, though I presume it could be better documented. Not all Nix packages have the same internal structure, and dev-env needs to be able to find the appropriate `bin` directory within them. For most packages, `dade-exec-nix-tool` works, but for some you'll need `dade-exec-nix-bin-tool` instead. So the linking step must become:

```
ln -s ../lib/dade-exec-nix-bin-tool dev-env/bin/jq
```

I don't know of an easy way to predict which packages will need which linking tool; I usually just try `dade-exec-nix-tool` first, as that's the one that works most often, and switch to `dade-exec-nix-bin-tool` if there is any issue. I have not yet found a package for which neither worked, but I suppose that might happen. If this happens to you, at this point I'm afraid you'd be on your own to debug it.
